# Generated by Django 5.1.3 on 2024-12-04 16:30

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_of_trades', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField()),
                ('volume_weighted_average', models.DecimalField(decimal_places=6, max_digits=10)),
                ('raw_timestamp', models.CharField(blank=True, help_text='Non transformed timestamp string or int or float', max_length=120, null=True)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 week')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_quotes', to='market.company')),
            ],
            options={
                'unique_together': {('company', 'time')},
            },
        ),
        migrations.CreateModel(
            name='ForexQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_of_trades', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField()),
                ('volume_weighted_average', models.DecimalField(decimal_places=6, max_digits=10)),
                ('raw_timestamp', models.CharField(blank=True, help_text='Non transformed timestamp string or int or float', max_length=120, null=True)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 week')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_quotes', to='market.company')),
            ],
            options={
                'unique_together': {('company', 'time')},
            },
        ),
    ]
