# Generated by Django 5.1.4 on 2024-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cryptoquote_forexquote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockQuote',
            new_name='Quote',
        ),
        migrations.AlterUniqueTogether(
            name='forexquote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forexquote',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('stock', 'Stock')], default='stock', max_length=10),
        ),
        migrations.DeleteModel(
            name='CryptoQuote',
        ),
        migrations.DeleteModel(
            name='ForexQuote',
        ),
    ]
